service: my-service

functions: ${file(./resources/functions.yml)}
resources: ${file(./resources/resources.yml)}

provider:
  name: aws
  region: 'eu-central-1'
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    test: test

custom:
  serverless-offline:
    httpPort: 4000
    useChildProcesses: true

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

package:
  individually: true
  packager: 'yarn' # needed to install npm private packages

plugins:
  - serverless-webpack
  - serverless-offline
