service: my-service

functions: ${file(./resources/functions.yml)}
# resources: ${file(./resources/resources.yml)}

provider:
  name: aws
  region: 'eu-central-1'
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    test: test
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

custom:
  serverless-offline:
    httpPort: 4000

  webpack:
    packager: yarn
    webpackConfig: webpack.config.ts
    includeModules:
      forceExclude:
        - aws-sdk

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
